set t_Co=256

set nocompatible              " be iMproved, required
filetype off                  " required
syntax on
"set mouse=a
set background=dark

" Auto indent
filetype indent on
filetype plugin indent on     " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#rc()
let mapleader="\<space>"
let g:solarized_termcolors=256

map <Leader>s :source $MYVIMRC<CR>
map <Leader>e :vs $MYVIMRC<CR>

set pastetoggle=<F10>
set number
set noswapfile
set autoindent
set hlsearch
set ignorecase
set smartcase
set nobackup
set autoread
set laststatus=2
set ttimeoutlen=50
" a combination of spaces and tabs are used to simulate tab stops at a width
" other than the (hard)tabstop
set softtabstop=4
set smarttab
set expandtab
set tabstop=4
set shiftwidth=4

set complete=.,b,u,]

" gvim
if has('gui_running')
    set go-=T
    set guifont=Liberation\ Mono\ 8
    set go-=r
    set go-=L
endif

call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'gmarik/vundle'
Plugin 'ervandew/supertab'
Plugin 'henrik/vim-qargs'
Plugin 'tpope/vim-sensible'
Plugin 'jdonaldson/vaxe'
Plugin 'altercation/vim-colors-solarized'
Plugin 'plasticboy/vim-markdown'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-rails.git'
Plugin 'scrooloose/nerdtree.git'
Plugin 'scrooloose/nerdcommenter'
Plugin 'jlanzarotta/bufexplorer'
Plugin 'L9'
Plugin 'justinmk/vim-sneak'
" Plugin 'Lokaltog/vim-easymotion'
Plugin 'groenewege/vim-less'
Plugin 'tpope/vim-surround'
Plugin 'kien/ctrlp.vim.git'
Plugin 'tomtom/tcomment_vim'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'flazz/vim-colorschemes'
Plugin 'https://github.com/mileszs/ack.vim.git'
call vundle#end()      

let g:ctrlp_custom_ignore = 'dist\|export\|node_modules\|DS_Store\|git'
let g:ctrlp_working_path_mode = 2
let g:ctrlp_max_depth = 5

" Shortcuts
map <C-k>b :NERDTreeToggle<CR>
imap jk <Esc>
" format the entire file
nmap <leader>fef ggVG=
map <silent><leader>t <leader>be<Down>t
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
noremap <tab> <c-w><c-w>
nnoremap <leader>l <C-^>
nmap Y y$

if executable("ag")
    let g:ackprg = 'ag --nogroup --nocolor --column'
endif

colorscheme default

" automatic formatting
autocmd BufWritePre *.slim :%s/\s\+$//e
autocmd BufWritePre *.rb :%s/\s\+$//e
autocmd BufWritePre *.hx :%s/\s\+$//e

au BufReadPost *.hxp set syntax=haxe
au BufReadPost *.hx set syntax=haxe
au BufReadPost *.md set syntax=markdown

