# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="clean"

plugins=(git zsh-syntax-highlighting vi-mode rails vi-like fasd)

# User configuration

export PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.rvm/bin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

export KEYTIMEOUT=1
export DISABLE_AUTO_TITLE="true"

# ctrl-r starts searching history backward
bindkey '^r' history-incremental-search-backward

source ~/dotfiles/bash/bash_aliases
bindkey '^U' backward-kill-line
bindkey '^Y' yank
