# Path to your oh-my-zsh installation.
export ZSH=/Users/ben/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="fishy"

plugins=(git jira zsh-syntax-highlighting vi-mode rails brew vi-like fasd)

# User configuration

export PATH="$PATH:/Users/ben/.rvm/gems/ruby-2.3.0@braavos/bin:/Users/ben/.rvm/gems/ruby-2.3.0@global/bin:/Users/ben/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ben/.rvm/bin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

export KEYTIMEOUT=1

# ctrl-r starts searching history backward
bindkey '^r' history-incremental-search-backward

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

source ~/dotfiles/bash/bash_aliases

export JIRA_URL="https://fundthrough.atlassian.net"
